classpath=

url=jdbc:sqlserver://apitosql.database.windows.net:1433;database=apitosql;encrypt=true;

username=liquibase_user1
password=StrongP@ssword123!

driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

changeLogFile=database/changelog/db.changelog-master.xml
